"""empty message

Revision ID: 27ee61ffdc72
Revises: 
Create Date: 2021-05-05 22:21:18.706552

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27ee61ffdc72'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('daily_amount', sa.Integer(), nullable=True),
    sa.Column('clear_before_add', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volunteer_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=True),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('volunteer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('surname', sa.String(length=256), nullable=True),
    sa.Column('callsign', sa.String(length=256), nullable=True),
    sa.Column('phone', sa.String(length=256), nullable=True),
    sa.Column('email', sa.String(length=256), nullable=True),
    sa.Column('photo', sa.BLOB(), nullable=True),
    sa.Column('volunteer_type_id', sa.Integer(), nullable=False),
    sa.Column('feed_type_id', sa.Integer(), nullable=False),
    sa.Column('ref_to_id', sa.Integer(), nullable=True),
    sa.Column('has_signed_approval', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['feed_type_id'], ['feed_type.id'], ),
    sa.ForeignKeyConstraint(['ref_to_id'], [u'volunteer.id'], ),
    sa.ForeignKeyConstraint(['volunteer_type_id'], ['volunteer_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feed_balance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feed_transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('volunteer_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=True),
    sa.Column('dtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feed_transaction')
    op.drop_table('feed_balance')
    op.drop_table('volunteer')
    op.drop_table('volunteer_type')
    op.drop_table('feed_type')
    # ### end Alembic commands ###
