"""empty message

Revision ID: 423576b9df3a
Revises: 4df70e5b2e45
Create Date: 2021-05-10 11:21:09.335055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '423576b9df3a'
down_revision = '4df70e5b2e45'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteer', sa.Column('short_uuid', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('volunteer', 'short_uuid')
    # ### end Alembic commands ###
