"""empty message

Revision ID: 4df70e5b2e45
Revises: 6dd2cc3bf440
Create Date: 2021-05-10 10:43:26.381415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4df70e5b2e45'
down_revision = '6dd2cc3bf440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.Column('is_federal', sa.Integer(), nullable=True),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['lead_id'], ['volunteer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vol_dept_link',
    sa.Column('volunteer_id', sa.Integer(), nullable=True),
    sa.Column('department_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteer.id'], )
    )
    op.add_column(u'QR__codes', sa.Column('is_valid', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'QR__codes', 'is_valid')
    op.drop_table('vol_dept_link')
    op.drop_table('department')
    # ### end Alembic commands ###
