"""empty message

Revision ID: 6dd2cc3bf440
Revises: a2bba7e146e1
Create Date: 2021-05-09 23:43:57.013967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6dd2cc3bf440'
down_revision = 'a2bba7e146e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed_transaction', sa.Column('hwo', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feed_transaction', 'hwo')
    # ### end Alembic commands ###
