"""empty message

Revision ID: 9342d65045ee
Revises: 423576b9df3a
Create Date: 2021-06-23 00:00:38.144682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9342d65045ee'
down_revision = '423576b9df3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('feed_transaction', sa.Column('trhash', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('feed_transaction', 'trhash')
    # ### end Alembic commands ###
