"""empty message

Revision ID: 945e60d23f7f
Revises: 9342d65045ee
Create Date: 2021-06-23 12:00:02.523385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '945e60d23f7f'
down_revision = '9342d65045ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transport_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('presence',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('arrival', sa.DateTime(), nullable=True),
    sa.Column('departure', sa.DateTime(), nullable=True),
    sa.Column('transport_type_id', sa.Integer(), nullable=False),
    sa.Column('needToMeet', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['transport_type_id'], ['transport_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vol_pres_link',
    sa.Column('volunteer_id', sa.Integer(), nullable=True),
    sa.Column('presence_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['presence_id'], ['presence.id'], ),
    sa.ForeignKeyConstraint(['volunteer_id'], ['volunteer.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vol_pres_link')
    op.drop_table('presence')
    op.drop_table('transport_type')
    # ### end Alembic commands ###
